#!/usr/bin/env python2
"""
Name :          applymethods/feh
Created :       August 28 2016
Author :        Will Pittman
Contact :       willjpittman@gmail.com
________________________________________________________________________________
Description :  Applies BG using feh

               Both args/kwds simply pass commandline
               arguments to feh.
________________________________________________________________________________
"""

import sys
import os
import json
import shlex
import logging
import subprocess

logger = logging.getLogger(__name__)

DEFAULT_ARGS=[ '--bg-scale', '{filepath}' ]
DEFAULT_KWDS={}


def parse_stdin():
    stdin       = json.loads(sys.stdin.read())
    specialvars = stdin['specialvars']


    ## Defaults (parse with specialvars)
    args  = [ arg.format(**specialvars) for arg in DEFAULT_ARGS ]
    kwds  = {}
    for (kwd,val) in kwds.items():
        kwds[ kwd.format(**specialvars) ] = val.format(**specialvars)

    ## loglevel



    ## Customized
    if 'args' in stdin:
        if stdin['args']:
            args = stdin['args']
    if 'kwds' in stdin:
        if stdin['kwds']:
            kwds = stdin['kwds']


    return (stdin,args,kwds)

def logging_setup(stdin):
    loglevel = logging.INFO

    if 'loglevel' in stdin:
        loglevel = stdin['loglevel']

    logging.basicConfig( level=loglevel )

def run(args,kwds):
    """
    passes all arguments, then all keywords to feh
    then run command.
    """


    if len(args) == 1 and not kwds:
        cmd = shlex.split( 'feh %s' % args[0] )

    else:
        cmd = ['feh']
        cmd.extend(args)
        for key,val in kwds.items():
            cmd.append( key )
            cmd.append( val )

    logger.debug( 'subprocess.call( %s )' % repr(cmd) )
    subprocess.call( cmd )


if __name__ == '__main__':
    (stdin,args,kwds) = parse_stdin()
    logging_setup( stdin )
    run( args, kwds )

