#!/usr/bin/env python2
"""
Name :          conditions/is_default.py
Created :       August 28 2016
Author :        Will Pittman
Contact :       willjpittman@gmail.com
________________________________________________________________________________
Description :   Always returns True. Using this condition on one of your
                configured archives marks it as the default.
________________________________________________________________________________
"""
import json
import sys


print( json.dumps({'return':True}) )
sys.exit(0)

