#!/usr/bin/env python
###########################################################################################
# Name :          conditions/is_hostname
# Created :       August 29 2016
# Author :        Will Pittman
# Contact :       willjpittman@gmail.com
# _________________________________________________________________________________________
# Description :   Returns the computer's hostname
# _________________________________________________________________________________________
###########################################################################################

import json
import platform
import sys

print(json.dumps({'return': platform.node()}))
sys.exit(0)
