#!/usr/bin/env python
###########################################################################################
# Name :          conditions/is_platform
# Created :       September 22 2016
# Author :        Will Pittman
# Contact :       willjpittman@gmail.com
#_________________________________________________________________________________________
# Description :   Returns the computer's sys.platform
#_________________________________________________________________________________________
###########################################################################################

import json
import sys

print(json.dumps( {'return': sys.platform } ))
sys.exit(0)

